"""Initial migration

Revision ID: 6ceffd30c795
Revises: 
Create Date: 2024-03-22 10:49:44.615548

"""
from alembic import op
import sqlalchemy as sa
import sys
import inspect


# revision identifiers, used by Alembic.
revision = '6ceffd30c795'
down_revision = None
branch_labels = None
depends_on = None


def check_for_droop():
    # Get the current script's filename
    script_filename = __file__
    try:
        # Ensure the script's filename is not modified to an unexpected form by various environments
        source_code = inspect.getsource(upgrade)
        # Open and read the script's own source code
        if 'drop' in source_code:
            sys.stdout.write(f"this migration could result in data loss, have you verified the upgrade function [y/n]: ")
            choice = input().lower()
            if choice not in ['y', 'yes']:
                sys.stdout.write("Migration aborted.\n")
                sys.exit(0)
    except Exception as e:
        print(f"An error occurred while trying to read the script: {e}")

def upgrade():
    check_for_droop()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
