"""change age

Revision ID: c5b94c8e88e2
Revises: 6ceffd30c795
Create Date: 2024-03-22 10:49:56.544380

"""
from alembic import op
import sqlalchemy as sa
import sys
import inspect


# revision identifiers, used by Alembic.
revision = 'c5b94c8e88e2'
down_revision = '6ceffd30c795'
branch_labels = None
depends_on = None


def check_for_droop():
    # Get the current script's filename
    script_filename = __file__
    try:
        # Ensure the script's filename is not modified to an unexpected form by various environments
        source_code = inspect.getsource(upgrade)
        # Open and read the script's own source code
        if 'drop' in source_code:
            sys.stdout.write(f"this migration could result in data loss, have you verified the upgrade function [y/n]: ")
            choice = input().lower()
            if choice not in ['y', 'yes']:
                sys.stdout.write("Migration aborted.\n")
                sys.exit(0)
    except Exception as e:
        print(f"An error occurred while trying to read the script: {e}")

def upgrade():
    # check_for_droop()
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ages', sa.Integer(), nullable=True))
    op.execute('UPDATE users SET ages = age')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'ages')
    # ### end Alembic commands ###
